version: "3"
services:
  server:
    container_name: server
    restart: always
    build: ./
    image: arbitrator777/docker-swarm-example:0.0.2
    ports:
      - 3000:3000
    networks:
      - mynet
#    environment:
#      - API_SERVER_PORT=8080
networks:
    mynet:
