version: "3"
services:
  api-service:
    container_name: api-service
    restart: always
    build: ./api-service/
    ports:
      - "8080:8080"
    environment:
      - API_SERVER_PORT=8080 # is it mapped to outside port???
    depends_on:
      - db
  db:
    container_name: db
    image: mongo
    restart: always
    volumes:
      - /Volumes/Storage2/mongodb/data/db:/data/db  # TODO: document for mongodb path for development
    expose:
      - "27017"
#    command: ["service", "mongod", "start"] #sudo service mongod start
#    command: ["mongod"]
  frontend-service:
    container_name: frontend-service
    restart: always
    build: ./frontend-service/
    ports:
      - "8081:8081"
    environment:
      - FRONTEND_PORT=8081
